services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: secretpass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-network
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - laravel-network
# docker-compose.yml
  valkey:
    image: valkey/valkey
    container_name: valkey
    ports:
      - "6379:6379"
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  dbdata:


  # app:
  #   build: .
  #   # command: bash -c "composer run dev"
  #   volumes:
  #     - .:/var/www/html
  #   networks:
  #     - laravel-network

  # web:
  #   image: nginx:latest
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - .:/var/www/html
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - app
  #   networks:
  #     - laravel-network
